name: Publish Docker image to Docker Hub

# Запускать этот воркфлоу при каждом пуше в ветку main
on:
  push:
    branches: [ main ] # Используйте 'master', если у вас ветка называется так

jobs:
  # Задача сборки и публикации
  build_and_push:
    # Запускать на последней версии Ubuntu
    runs-on: ubuntu-latest
    
    steps:
      # 1. Скачиваем код из репозитория
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Входим в Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 3. Собираем и публикуем образ
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          # Контекст сборки - папка 1c-server, где лежит Dockerfile
          context: ./1c-server 
          # Мы хотим именно опубликовать образ
          push: true
          # Имя и тег образа
          tags: defin85/1c-server:latest 